### ISSUE TITLE
Custom dashboard access with authentication

### ISSUE THREAD

**Issue by djerfy** [djerfy/kubernetes-ingress-traefik#3]

**Comment by Flodu31** [comment]
Interested :)

**Comment by djerfy** [comment]
Thanks, review in progress via #4 ;)

**Comment by djerfy** [comment]
Authentication view (default: `traefik/traefik`):

![2020-03-17_19h54_02](https://user-images.githubusercontent.com/2886596/76891496-630fa780-6889-11ea-8cdf-cba80c5149ea.png)

Default dashboard view:

![2020-03-17_19h54_29](https://user-images.githubusercontent.com/2886596/76891509-67d45b80-6889-11ea-845c-4a2546925133.png)

Router view for `traefik-dashboard`:

![2020-03-17_19h55_14](https://user-images.githubusercontent.com/2886596/76891524-6dca3c80-6889-11ea-88db-cf95ce83b889.png)

Router details for `traefik-dashboard`:

![2020-03-17_19h55_46](https://user-images.githubusercontent.com/2886596/76891535-71f65a00-6889-11ea-80c5-cc89d9d7f460.png)

Traefik dashboard available via `traefik-dashboard.domain.tld` (customize in the `IngressRoute.yaml` file) and only in **http**. You can create the route in https if necessary.

Sorry for the documentation, this subject is in progress.

**Comment by Flodu31** [comment]
Waiting the update, thanks.
Florent

**Comment by djerfy** [comment]
Changes merged in branch `master`.
